apiVersion: v1
data:
  PGPASSWORD: cGFzczEyMw==
  PGUSER: YmVsbGlhcw==
kind: Secret
metadata:
  creationTimestamp: "2022-09-27T07:47:38Z"
  name: pg-user
  namespace: default
  resourceVersion: "13961"
  uid: afb8556c-fb8b-4a91-b2cd-830209cdb911
type: Opaque
